default:
  project_desc: Ardhi Initiative
  collection: ardhi
  tei_html_xsl: scripts/overrides/tei_to_html.xsl
  api_version: "2.0"
  threads: 20

development:
  site_url: https://servername.unl.edu/ardhi
  es_path: https://servername.unl.edu/elastic
  es_index: cdrhapidev-v2
  media_base: https://servername.unl.edu
  data_base: https://servername.unl.edu/media

production:
  site_url: https://ardhi.unl.edu
  es_path: https://cdrhapi.unl.edu/elastic
  es_index: cdrhapi-v2
  media_base: https://servername.unl.edu
  data_base: https://servername.unl.edu/media
